brew cask install java
brew cask install iterm2
brew cask install google-chrome
brew cask install caffeine
brew cask install chromecast
brew cask install cyberduck
brew cask install dropbox
brew cask install slack
brew cask install spotify
brew cask install visual-studio-code
brew cask install vlc
brew cask install virtualbox
brew cask install vagrant
brew cask install qlcolorcode
brew cask install qlstephen
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install quicklook-csv
brew cask install intellij-idea-ce
