brew cask install font-inconsolata
brew cask install font-josefin-sans
brew cask install font-lato
brew cask install font-liberation-mono-for-powerline
brew cask install font-liberation-sans
brew cask install font-lobster-two
brew cask install font-montserrat
brew cask install font-raleway
brew cask install font-roboto
brew cask install font-source-code-pro
brew cask install font-source-sans-pro
brew cask install font-source-serif-pro
